version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/portfolio
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file    
hooks:
  BeforeInstall:
    - location: deploy/before-install.sh
      runas: ec2-user
  ApplicationStart:
    - location: deploy/app-start.sh
      runas: ec2-user
  ApplicationStop:
    - location: deploy/app-stop.sh
      runas: ec2-user
