(function(g){var window=this;var K7=function(a,b){return g.aa[a]=b},vta=function(a,b){var c=new g.eJ;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.isDefault=!1;c.G=a.G;c.F=a.F;c.H=a.H;c.g=b;return c},L7=function(a){return a.g?a.g.languageCode:a.o},M7=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.fJ(a),kind:a.B,name:a.C,id:a.ya,is_servable:a.M,is_default:a.isDefault,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},N7=function(){this.timestamp=this.cf=0;
this.g=!1},O7=function(){this.g=0},P7=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new N7}this.g=this.o=this.Fc=0;this.style=new O7;this.C=a;this.B=0},Q7=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.cf){0==c&&(c=m,d=q);var n=String.fromCharCode(r.cf),v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.cf||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.cf,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},R7=function(a){return a.A[a.Fc][a.o]},S7=function(a,b,c){2<=b&&1<
a.o&&(--a.o,R7(a).cf=0);
var d=R7(a);d.timestamp=a.C.o+0;a:{switch(b){case 0:b=wta[(c&127)-32];break a;case 1:b=xta[c&15];break a}b=0}d.cf=b;32>a.o&&a.o++},yta=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].hm(a.A[c+e][f])},T7=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},U7=function(a){a.Fc=0<a.g?a.g:1;
a.o=1;T7(a,0,15)},V7=function(a){this.B=a;
this.C=0;this.style=new O7;this.D=new P7(a);this.F=new P7(a);this.G=new P7(a);this.o=this.D;this.A=this.F;this.g=this.o},W7=function(a,b,c){var d=a.o;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:Q7(d,c),U7(a.o),U7(a.A),d.Fc=15,d.g=b}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;d.o=1;d.g!=b&&(d.g>b?(Q7(d,c),T7(d,d.Fc-d.g,b)):d.Fc<b&&(b=d.g),d.g=b)},zta=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},Ata=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},X7=function(){this.o=this.A=this.g=0},Cta=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Ll:a,
Ml:b,result:0};a=Bta[a];b=Bta[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{Ll:a,Ml:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Ll:a,Ml:b,result:2};return{Ll:a,Ml:b,result:3}},Y7=function(a,b,c,d,e){g.mT.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Z7=function(a,b,c,d,e,f,k){g.mT.call(this,a,a+b,{priority:c,
namespace:"captions"});this.windowId=d;this.text=e;this.C=f||!1;this.o=k||null},$7=function(a){this.o=a;
this.g=new X7;this.C=0;this.A=new V7(a);this.D=new V7(a);this.B=this.A},Dta=function(a,b,c,d){a.g.update();
b=Cta(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ll;c=b.Ml;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&S7(e,0,b),c&96&&S7(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&Q7(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Fc;break;case 3:if(d!=c.Fc){if(d<c.g&&(d=c.g,d==c.Fc))break;var f=1+c.Fc-c.g,k=1+d-c.g;yta(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));T7(c,b,e)}}c.Fc=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:S7(b.g,0,32);break a;case 48:57==c?(b=b.g,R7(b).cf=0,32>b.o&&b.o++):S7(b.g,1,c&15)}break;case 2:c&32&&S7(b.g,2,c&31);break;case 3:c&32&&S7(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:zta(b);break;
case 33:b=b.g;1<b.o&&(--b.o,R7(b).cf=0);break;case 36:b=b.g;d=R7(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:W7(b,2,d);break;case 38:W7(b,3,d);break;case 39:W7(b,4,d);break;case 40:S7(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);U7(d);Ata(b);break;case 43:Ata(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:Q7(a,d)}T7(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Fc){++a.Fc;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Fc<a.g&&(a.Fc=a.g));b=a.Fc-a.g+1;Q7(a,d);yta(a,b,b+1,a.g-1);T7(a,a.Fc,1)}break;case 46:T7(b.A,0,15);break;case 47:Q7(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;zta(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},Eta=function(){},Fta=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=
!0;
break;case "i":k.Wq=!0;break;case "u":k.rs=!0;break;case "font":var m=f.getAttribute("color");a8.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new Z7(a,b,c,d,n.nodeValue,e||0<m,g.Vb(k)?void 0:k));else{var q={};g.Aa(q,k);Fta(a,b,c,d,e||0<m,n,q,l)}}},c8=function(a){var b="_"+b8++;
return new Y7(0,0x8000000000000,0,b,a||{})},Hta=function(a){var b=Gta(a);
b.toString(16);if(1380139777!=b)return!1;a.version=d8(a);if(1<a.version)return!1;d8(a);d8(a);d8(a);return!0},e8=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.A=new window.DataView(a);this.o=[]},d8=function(a){var b=a.g;
a.g+=1;return a.A.getUint8(b)},Gta=function(a){var b=a.g;
a.g+=4;return a.A.getUint32(b)},f8=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new $7(this);this.D=new $7(this);this.g=[];this.clear()},Ita=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,Dta(a.C,b,c,d))},Jta=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?Ita(a,d.Iu,d.Ju,b):1==d.type&&a.A&496&&Dta(a.D,d.Iu,d.Ju,b)}a.g.length=0},Kta=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.bs("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Fta(d,e,k,b,f,a.firstChild,{},c)},g8=function(){},Lta=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},h8=function(){this.za=[]},i8=function(){this.o=null},Mta=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Wq=!0;break;case "u":l.rs=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new Z7(b,c,d,e.id,q.nodeValue,f||0<n,g.Vb(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.Aa(r,l);Mta(a,b,c,d,e,!0,q,r,m)}}},j8=function(a){a=a.split(":");
for(var b=0,c=0;c<a.length;c++)b=60*b+(0,window.parseFloat)(a[c]);return 1E3*b},Nta=function(){this.A=[];
this.g=[];this.o=-1},k8=function(a,b){return b?a.g.concat(a.A):a.g},l8=function(a,b){switch(b.B){case "asr":Ota(b,a.A);
break;default:if(b.isDefault||0>a.o)a.o=a.g.length;Ota(b,a.g)}},Ota=function(a,b){g.bb(b,(0,g.z)(a.J,a))||b.push(a)},Pta=function(a,b){var c=g.ab(a.g,(0,g.z)(b.J,b));
-1!=c&&(a.o=c)},m8=function(a,b){this.B=a;
this.o="CC3"==b.D?4:0;this.A=new f8(!0);this.A.A=1<<this.o},n8=function(a){this.o={};
this.C={};this.D={};this.A="_"+b8++;this.B=a},o8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},p8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},q8=function(a,b){var c=o8(a,b);
if(void 0!=c)return c},r8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return a8.test(c),c},Qta=function(a,b){var c={},d=b.getAttribute("ws");
g.Aa(c,d?a.D[d]:a.B);d=q8(b,"mh");null!=d&&(c.gr=d);d=q8(b,"ju");null!=d&&(c.textAlign=d);d=q8(b,"pd");null!=d&&(c.yj=d);d=r8(b,"wfc");null!=d&&(c.windowColor=d);d=o8(b,"wfo");void 0!=d&&(c.ci=d/255);return c},Rta=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Aa(c,a.C[d]);d=q8(b,"ap");null!=d&&(c.Hg=d);d=o8(b,"cc");null!=d&&(c.Yu=d);d=o8(b,"ah");null!=d&&(c.Ph=d);d=o8(b,"rc");null!=d&&(c.Hn=d);d=o8(b,"av");null!=d&&(c.Xh=d);return c},Sta=function(a,b,c){var d={};
g.Aa(d,Rta(a,b));g.Aa(d,Qta(a,b));c?(c=a.A,Lta(d,a.B)&&(d=a.B)):c=b.getAttribute("id")||"0";a=o8(b,"t");b=o8(b,"d")||0x8000000000000;return new Y7(a,b,0,c,d)},s8=function(){this.A={};
this.o=null},t8=function(a){this.A=a;
this.o=null},u8=function(a){if(!Tta.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Uta,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},v8=function(a,b,c,d,e){g.L.call(this);
this.J=b;this.F=new h8;this.g=null;this.C=d;this.A=this.o=null;this.M=c;this.B=e||!1;this.G=new g.ou(this.H,1E3,this);g.M(this,this.G);b.addEventListener("seekto",this.D,this);this.D(b.getCurrentTime());this.H()},w8=function(a){this.Uw=!!a;
this.g=new Nta;this.D=[];this.o=null},Wta=function(a){var b={};
if(a=L7(a))b.lang=a,Vta.test(a)&&(b.yj=1);return b},Xta=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.y(b)){if("WEBVTT"==b.substring(0,6))return a.o||(a.o=new i8),a.o.g(b,d);b=g.bs(b);if(!b||!b.firstChild)return[];a.o||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.o=new n8(Wta(c)):a.o=new s8:a.o=new t8(Wta(c)));return a.o.g(b,d)}try{var f;if(g.y(b))f=!1;else{var k=new e8(b,0,0);f=Hta(k)}if(f)return a.o||(a.o=new m8(e,c)),a.o.g(b,d)}catch(l){g.dF(l)}return[]},Yta=function(a,b){return g.bb(k8(a.g,!0),function(a){return a.toString()==
b})},x8=function(a,b,c,d,e,f){var k={};
g.Aa(k,b);g.Aa(k,a.params);g.Aa(k,c);var l={};g.Aa(l,b.gb);a.params.gb&&g.Aa(l,a.params.gb);g.Aa(l,c.gb);k.gb=l;g.X.call(this,{K:"div",X:"caption-window",Z:{id:"caption-window-"+a.id,dir:1==k.yj?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},R:[{K:"span",X:"captions-text"}]});this.B=[];this.H=!1;this.C=a;this.F=[];this.G=[];this.Aa=e;this.wa=f;this.D=null;this.N=.96*e;this.ma=.96*f;this.g=k;this.pa=c;this.A=this.ua["captions-text"];this.ga=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.J=d/360*16;this.type=0;this.aa=this.J*Zta(l);a=new g.wG(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.ZR,this);a.subscribe("dragmove",this.YR,this);a.subscribe("dragend",this.XR,this);this.da=this.ca=0;a="";this.g.ci&&(a=u8(this.g.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.g.ci+")");b={"background-color":a,display:!1===this.g.isVisible?"none":"","text-align":$ta[this.g.textAlign]};this.ga&&(b["border-radius"]=a?this.aa/
8+"px":"");g.fh(this.element,b);switch(this.g.Hg){case 0:case 1:case 2:g.R(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.R(this.element,"ytp-caption-window-bottom")}},Zta=function(a){var b=1+.25*(a.Bi||0);
if(0==a.offset||2==a.offset)b*=.8;return b},y8=function(a,b){var c={},d=b.background?b.background:a.g.gb.background;
if(null!=b.Ke||b.background){var e=null!=b.Ke?b.Ke:a.g.gb.Ke,f=u8(d);c.background="rgba("+f[0]+","+f[1]+","+f[2]+","+e+")";a.ga&&(c["box-decoration-break"]="clone",c["border-radius"]=a.aa/8+"px")}if(null!=b.Bi||null!=b.offset)c["font-size"]=a.J*Zta(b)+"px";var k=1,l=b.color||a.g.gb.color;if(b.color||null!=b.jh)f=u8(l),k=null==b.jh?a.g.gb.jh:b.jh,f="rgba("+f[0]+","+f[1]+","+f[2]+","+k+")",c.color=f,c.fill=f;f=b.zh;0==f&&(f=null);!f&&1==k&&(d==l&&1==e||0==e&&a.g.windowColor==l&&1==a.g.ci)&&(f=3);if(f){var d=
"rgba(34, 34, 34, "+k+")",m="rgba(204, 204, 204, "+k+")";b.Nu&&(m=d=b.Nu);var l=a.J/16/2,n=Math.max(l,1),q=Math.max(2*l,1),e=Math.max(3*l,1),r=Math.max(5*l,1),k=[];switch(f){case 4:for(f=e;f<=r;f+=l)k.push(q+"px "+q+"px "+f+"px "+d);break;case 1:l=2<=window.devicePixelRatio?.5:1;for(f=n;f<=e;f+=l)k.push(f+"px "+f+"px "+d);break;case 2:k.push(n+"px "+n+"px "+m);k.push(-n+"px "+-n+"px "+d);break;case 3:for(f=0;5>f;f++)k.push("0 0 "+q+"px "+d)}c["text-shadow"]=k.join(", ")}f="";switch(b.fontFamily){case 1:f=
'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:f='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:f='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:f='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:f='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:f=g.EG()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';
break;case 0:case 4:f='Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}f&&(c["font-family"]=f);f=b.offset;null==f&&(f=a.g.gb.offset);switch(f){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Wq&&(c["font-style"]="italic");b.rs&&(c["text-decoration"]="underline");b.oq&&(c.visibility="hidden");return c},aua=function(a,b,c){a.H=a.H||!!c;
var d={};g.Aa(d,a.g.gb);g.Aa(d,c||b.o);g.Aa(d,a.pa.gb);var e=a.F[0],f;if(e&&d.background==e.background&&d.Ke==e.Ke&&!!d.oq==!!e.oq&&d.zh==e.zh){for(c=0;c<a.F.length;c++)if(Lta(d,a.F[c])){f=a.G[c];break}if(!f){c={};for(var k in d)d[k]!=e[k]&&(c[k]=d[k]);f=g.te("SPAN");g.fh(f,y8(a,c));a.G[0].appendChild(f);c=1}a.G.length=c;a.F.length=c}else a.G.length=0,a.F.length=0,f=g.te("SPAN"),g.fh(f,y8(a,d)),a.A.appendChild(f);a.D&&a.D.parentNode!=f&&(g.Ae(a.D),f.appendChild(a.D));e=(k=g.y(b.text))?b.text.split("\n"):
[b.text];for(c=0;c<e.length;c++){var l=e[c];if(0<c||0==a.B.length||!b.C){if(0<c||0!=a.B.length){var m=g.te("BR");f.appendChild(m)}f.appendChild(g.ue("\u00a0"));a.D=g.ue("\u00a0");f.appendChild(a.D)}l&&(m=a.D,m.parentNode&&m.parentNode.insertBefore(k?g.ue(l):l,m))}a.F.push(d);a.G.push(f);a.B.push(b)},z8=function(a,b,c,d){w8.call(this,d);
c=c||g.sF(a).hl||"";c=c.split("_").join("-");this.B=g.uF(a,{hl:c});this.C=b;this.F={};this.A=null},A8=function(a,b,c,d,e,f){x8.call(this,a,b,c,d,e,f);
g.R(this.element,"ytp-caption-window-rollup");this.type=2;this.L=this.S=0;this.M=window.NaN;this.ia=null;this.ea=new g.ou(this.ra,433,this);g.M(this,this.ea)},B8=function(a){if(!a.L){var b=g.te("SPAN");
g.fh(b,y8(a,a.g.gb));a.A.appendChild(b);b.appendChild(g.ue("M"));var c=b.offsetHeight,d=g.te("BR");b.appendChild(d);b.appendChild(g.ue("M"));a.L=b.offsetHeight-c;a.A.removeChild(b)}return a.L},C8=function(a,b,c,d,e,f){x8.call(this,a,b,c,d,e,f);
this.type=1},D8=function(a,b){w8.call(this);
this.B=a;this.W=b;this.A=null},E8=function(a){w8.call(this,a.Rl);
this.A=null;this.C=void 0;this.B=null;this.D=a.captionTranslationLanguages},bua=function(a){for(var b in a)delete a[b]},I8=function(a){g.XV.call(this,a);
g.EE();this.Y=g.Y(a);this.B=a.getVideoData();this.ea=g.AV(a);this.W=a;var b=null,c=g.fE("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.UD(c));this.aa=b;this.C={gb:{}};this.D={gb:{}};this.J=[];this.H={};this.N={};this.M=!1;this.ia="1"==this.B.Rb.cc_auto_caps||"1"==this.Y.J.cc_auto_caps;c=b=this.A=this.o=this.G=this.F=this.L=this.da=null;F8(this)||(b=new g.ou(this.AA,0,this),g.M(this,b),c=new g.ou(this.OO,2E3,this),g.M(this,c));this.ba=b;this.ga=c;this.S=new g.BM(this);g.M(this,this.S);
F8(this)||this.S.V(a,"resize",this.us);this.S.V(a,"onPlaybackAudioChange",this.AK);this.S.V(a,"crn_captions",this.HR,this);this.S.V(a,"crx_captions",this.IR,this);G8(this,H8(this,"display-settings")||{});cua(this)&&this.load()},F8=function(a){return"3"!=a.Y.A?!1:!!a.W.app.F.Rn()},dua=function(a){var b;
a.B.captionTracks.length&&(b=a.g.di().Fu);if("FORCED_ON"==b||1==a.Y.Jg||1==a.B.Jg||"alwayson"==a.B.vf("yt:cc"))return!0;if(2==a.Y.Jg){var c=H8(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==a.B.vf("yt:cc")},cua=function(a){return F8(a)?!a.B.Ca:a.B.captionTracks.length&&a.g.di().Zj?!0:dua(a)},fua=function(a,b){if(!g.Y(a.g).experiments.g("legacy_default_captions")){if(a.o){var c=k8(a.o.g,b||a.ia),d=H8(a,"recent-langs");
if(d){for(var e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(d[e]==L7(c[f]))return c[f];for(e=0;e<d.length;e++)for(var k=d[e].match(eua)[0],f=0;f<c.length;f++){var l=L7(c[f]).match(eua)[0];if(k==l)return c[f]}}return a.G&&a.G.xi?a.G.xi:c[0]||J8(a)}return null}c=null;a.o&&(c=a.o.Nv(),!c&&b&&(c=k8(a.o.g,!0)[0]),c||!b&&!a.ia||(d=a.o.g.A,d.length&&(c=Yta(a.o,d[0].toString()))),c||(c=J8(a)));return c},J8=function(a){return g.Y(a.g).experiments.g("legacy_default_captions")?a.o.Pv():a.G&&a.G.Zj},K8=function(a,
b,c,d){a.loaded&&a.unload();
null!=c&&(a.M=c);a.A=b;a.load(d)},G8=function(a,b,c){var d=L8.gb;
a.C={};g.Aa(a.C,L8);a.C.gb={};g.Aa(a.C.gb,d);a.D={gb:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;a8.test(f);e.gb.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;a8.test(f);e.gb.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||L8.windowColor;a8.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ke);e.gb.Ke=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;null==f&&(f=d.Bi);e.gb.Bi=f;e=b.textOpacityOverride?
a.D:a.C;f=b.textOpacity;null==f&&(f=d.jh);e.gb.jh=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=L8.ci);e.ci=f;e=b.charEdgeStyleOverride?a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.zh);e.gb.zh=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.gb.fontFamily=f;a.loaded&&a.us();c&&M8(a,"display-settings",b)},hua=function(a,b){if(b&&!a.F){var c=c8({yj:0,
lang:"en"});a.F=[c,new Z7(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.MV(a.g,a.F)}else!b&&a.F&&(gua(a,a.F),a.F=null)},gua=function(a,b){g.OV(a.g,b);
(0,g.F)(b,function(a){g.nb(this.J,a)},a);
a.ba.Be()},iua=function(a,b){return a&&g.y(a)&&a8.test(a)?a:b},jua=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},lua=function(a,b){if(a&&g.y(a)){var c=kua.indexOf(a);
return-1!=c?c:b}return b},nua=function(a,b){if(a&&g.y(a)){var c=mua.indexOf(a);
return-1!=c?c:b}return b},oua=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?g.Ud(a,-2,4):b},H8=function(a,b){if(!a.aa)return null;
var c;try{c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},M8=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.yM.prototype.Rn=K7(6,function(){return!!this.g.textTracks});
g.y_.prototype.Rn=K7(5,function(){return!1});
g.yM.prototype.Il=K7(4,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.y_.prototype.Il=K7(3,function(){});
g.OL.prototype.Gm=K7(2,function(a){return(a=g.PL(this,a))?a.o:0});
g.TN.prototype.Gm=K7(1,function(){return 0});
g.eJ.prototype.J=K7(0,function(a){return a?this.toString()==a.toString():!1});
var xta=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],wta=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632];N7.prototype.hm=function(a){this.cf=a.cf;this.timestamp=a.timestamp;this.g=a.g};
N7.prototype.reset=function(){this.timestamp=this.cf=0;this.g=!1};
O7.prototype.set=function(a){this.g=a};
O7.prototype.get=function(){return this.g};
var Bta=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];
P7.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Fc=1};
var b8=0;V7.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
X7.prototype.clear=function(){this.g=0};
X7.prototype.update=function(){this.g=2==this.g?1:0};
X7.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
g.A(Y7,g.mT);g.A(Z7,g.mT);var a8=/^#(?:[0-9a-f]{3}){1,2}$/i,Tta=/^#(?:[0-9a-f]{3}){1,2}$/i;$7.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};
Eta.prototype.B=function(){};
var Uta=/#(.)(.)(.)/,pua=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/,qua=/(?:\r\n|\r|\n){2,}/,rua=/^NOTE/,sua=0;g.p(e8,Eta);e8.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+b8++;c=c/1E3-this.F;d=d/1E3-this.F;a=new Y7(c,d-c,5,f,{textAlign:0,Hg:0,Ph:2.5*b,Xh:5.33*a});e=new Z7(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
f8.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
f8.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var Vta=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;h8.prototype.contains=function(a){a=g.xb(this.za,a);return 0<=a||0>a&&1==(-a-1)%2};
h8.prototype.length=function(){return this.za.length/2};
g.A(i8,g8);
i8.prototype.g=function(a,b){for(var c=[],d=a.split(qua),e=1;e<d.length;e++){var f=d[e],k=b,l=c;if(""!=f&&!rua.test(f)){var m=g.C4.exec(f);if(m&&3<=m.length){var n=j8(m[1]),m=j8(m[2])-n,f=f.substring(g.C4.lastIndex);g.C4.lastIndex=0;var k=n+k,n=m,q=f,m={};this.o||(this.o=c8({gr:0}),l.push(this.o));var r=this.o,f=5;if(0>q.indexOf("<"))l.push(new Z7(k,n,f,r.id,q,!1,g.Vb(m)?void 0:m));else{q=q.split(pua);1!=q.length&&(f=6,r="_"+sua++,r=new Y7(k,n,f,r,{}),l.push(r));for(var v=k,w=0;w<q.length;w++){var B=q[w];
if(0==w%2){var G=g.bs("<html>"+B+"</html>"),S;G.getElementsByTagName("parsererror").length?(S=G.createElement("span"),S.appendChild(G.createTextNode(B))):S=G.firstChild;Mta(this,v,n-(v-k),f,r,0<w,S,m,l)}else v=j8(B)}}}g.C4.lastIndex=0}}return c};
g.p(m8,g8);m8.prototype.g=function(a){a=new e8(a,0,this.B);if(Hta(a)){for(;a.g<a.A.byteLength;)for(0==a.version&&(a.D=Gta(a)*(1E3/45)),a.C=d8(a);0<a.C;a.C--){var b=d8(a),c=d8(a),d=d8(a);b&4&&(b&3)==this.o&&(0==this.o||1==this.o)&&(b=this.A,b.g.push({time:a.D,type:this.o,Iu:c,Ju:d,order:b.g.length}))}Jta(this.A,a);return a.o}return[]};
g.A(n8,g8);
n8.prototype.g=function(a){a.firstChild.getAttribute("format");var b,c;a=a.firstChild.childNodes;for(var d=0;d<a.length;d++){var e=a[d];switch(e.tagName){case "head":b=e;break;case "body":c=e}}if(b)for(b=b.childNodes,a=0;a<b.length;a++){var f=b[a];switch(f.tagName){case "pen":var e=f.getAttribute("id"),d=this.o,k=f,f={},l=k.getAttribute("p");l&&g.Aa(f,this.o[l]);l=p8(k,"b");null!=l&&(f.bold=l);l=p8(k,"i");null!=l&&(f.Wq=l);l=p8(k,"u");null!=l&&(f.rs=l);l=q8(k,"et");null!=l&&(f.zh=l);l=q8(k,"of");
null!=l&&(f.offset=l);l=r8(k,"bc");null!=l&&(f.background=l);l=r8(k,"ec");null!=l&&(f.Nu=l);l=r8(k,"fc");null!=l&&(f.color=l);l=q8(k,"fs");void 0!=l&&0!=l&&(f.fontFamily=l);l=o8(k,"sz");void 0!=l&&(f.Bi=l/100-1);l=o8(k,"bo");void 0!=l&&(f.Ke=l/255);k=o8(k,"fo");void 0!=k&&(f.jh=k/255);d[e]=f;break;case "ws":d=f.getAttribute("id");this.D[d]=Qta(this,f);break;case "wp":d=f.getAttribute("id"),this.C[d]=Rta(this,f)}}b=[];if(c){a={};c=c.childNodes;for(var d=void 0,m,e=0;e<c.length;e++)switch(f=c[e],f.tagName){case "w":var n=
Sta(this,f,!1);(f=a[n.id])&&f.end>n.start&&(f.end=n.start);a[n.id]=n;b.push(n);break;case "p":var q=f,r=d,v=m,k=[],l=q.getAttribute("w")||this.A,w=!!p8(q,"a"),B=o8(q,"t")||0,G=o8(q,"d")||5E3;!v&&!w&&r&&r.windowId==l&&r.end>B&&(r.end=B);for(var r=w?6:5,v=this.o[q.getAttribute("p")],q=q.childNodes,S=0;S<q.length;S++){var I=q[S];0<S&&(w=!0);if("s"==I.tagName)var Oa=I,I=B,jb=G,ha=l,qd=w,Ub=r,Tf=Oa.textContent?Oa.textContent:"",Si=this.o[Oa.getAttribute("p")],Oa=o8(Oa,"t")||0,I=new Z7(I+Oa,jb-Oa,Ub,ha,
Tf,qd,Si);else I=new Z7(B,G,r,l,I.textContent||"",w,v);k.push(I)}d&&"\n"==d.text&&(d.text="");if(0<k.length)for(d=k[k.length-1],m=null!=f.getAttribute("d"),k[0].windowId==this.A&&(n=Sta(this,f,!0),b.push(n)),f=0;f<k.length;f++)l=k[f],k[f].windowId=n.id,n.o.push(l),b.push(l)}}return b};
g.A(s8,g8);
s8.prototype.g=function(a){var b=[];this.o||(this.o=c8(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=b,e=c.getAttribute("id");a:{var f=c,k=this.A[e];if(f.getAttribute("t")||f.getAttribute("start")){c=f.getAttribute("start")?1E3*(0,window.parseFloat)(f.getAttribute("start")):(0,window.parseInt)(f.getAttribute("t"),10);k&&(k.end>=c?k.end=c:k=null);switch(f.getAttribute("op")){case "kill":c=null;break a;case "define":k=null}k||
(k=c8());var l={};k&&(g.Aa(l,k.params),k=k.params.gb)&&(l.gb={},g.Aa(l.gb,k));f.getAttribute("rc")&&(l.Hn=(0,window.parseInt)(f.getAttribute("rc"),10));f.getAttribute("cc")&&(l.Yu=(0,window.parseInt)(f.getAttribute("cc"),10));f.getAttribute("ap")&&(k=(0,window.parseInt)(f.getAttribute("ap"),10),l.Hg=0>k||8<k?7:k);f.getAttribute("ah")&&(l.Ph=(0,window.parseInt)(f.getAttribute("ah"),10));f.getAttribute("av")&&(l.Xh=(0,window.parseInt)(f.getAttribute("av"),10));f.getAttribute("vs")&&(l.isVisible=!!f.getAttribute("vs"));
f.getAttribute("ju")&&(l.textAlign=(0,window.parseInt)(f.getAttribute("ju"),10));f.getAttribute("pd")&&(l.yj=1,0==(0,window.parseInt)(f.getAttribute("pd"),10)&&(l.yj=0));f.getAttribute("bc")&&(l.gb||(l.gb={}),l.gb.backgroundColor=f.getAttribute("bc"));f.getAttribute("bo")&&(l.gb||(l.gb={}),l.gb.Ke=(0,window.parseInt)(f.getAttribute("bo"),10)/100);f.getAttribute("fc")&&(l.gb||(l.gb={}),l.gb.color=f.getAttribute("fc"));f.getAttribute("sd")&&(l.rP=(0,window.parseInt)(f.getAttribute("sd"),10));k=(0,window.parseInt)(f.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(f.getAttribute("dur"))||0x8000000000000;f=f.getAttribute("id")||"0";c=new Y7(c,k,0,f,l)}else c=null}this.A[e]=c;d.push(c);break;case "text":for(d=b,e=[],Kta(a,this.o.id,e),c=0;c<e.length;c++)l=e[c],this.A[l.windowId]&&d.push(l)}a=a.nextSibling}return b};
g.A(t8,g8);t8.prototype.g=function(a){var b=[];this.o||(this.o=c8(this.A),b.push(this.o));a=a.firstChild.childNodes;for(var c=0,d=a.length;c<d;c++)Kta(a[c],this.o.id,b);return b};
var $ta=["left","right","center"],tua={oq:!0};g.A(v8,g.L);v8.prototype.P=function(){v8.O.P.call(this);this.J.removeEventListener("seekto",this.D,this);this.A&&this.A.abort()};
v8.prototype.D=function(a){this.g=g.$a(this.M.fk(a).g)};
v8.prototype.H=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.kl(a);if(a&&!this.A&&!(this.g&&30<this.g.startTime-this.J.getCurrentTime())){a=this.g;a=a.g.wo(a);if(!this.F.contains(a.g[0].o)){var b=g.eN(g.DN(a)),c={format:"RAW",td:(0,g.z)(this.L,this),withCredentials:!0};this.B&&(c.responseType="arraybuffer");this.A=g.xF(b,c);this.o=a;var b=this.F,c=this.o.g[0].o,d=g.xb(b.za,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.za[d-1]&&d<b.za.length&&1==b.za[d]-c?(g.lb(b.za,d),g.lb(b.za,d-1)):0<d&&1==
c-b.za[d-1]?b.za[d-1]=c:d<b.za.length&&1==b.za[d]-c?b.za[d]=c:(g.tb(b.za,d,0,c),g.tb(b.za,d+1,0,c)))}this.g=g.$a(a.g)}this.G.start()};
v8.prototype.L=function(a){(this.B?!a.response:!a.responseText)||400<=a.status||null===this.C||(this.B?this.C(a.response,1E3*this.o.g[0].startTime):this.C(a.responseText,1E3*this.o.g[0].startTime));this.A=this.o=null};
g.A(w8,g.L);w8.prototype.Nv=function(a){var b=this.g.o,c=k8(this.g,!0);a&&0>b&&0<c.length&&(b=0);return 0>b?null:c[b]};
w8.prototype.Pv=function(){return null};
w8.prototype.ud=function(){this.o=null};
w8.prototype.P=function(){w8.O.P.call(this);this.ud()};
g.A(x8,g.X);g.h=x8.prototype;g.h.ZR=function(a,b){var c=g.uh(this.element,this.element.parentElement);this.ca=a-c.x;this.da=b-c.y;g.R(this.element,"ytp-dragging")};
g.h.YR=function(a,b){var c=g.xh(this.element),d=a-this.ca-.02*this.Aa,e=b-this.da-.02*this.wa,f=(d+c.width/2)/this.N*3,f=Math.floor(g.Ud(f,0,2)),k=(e+c.height/2)/this.ma*3,k=Math.floor(g.Ud(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.N,d=100*g.Ud(d,0,1),c=(e+k/2*c.height)/this.ma,c=100*g.Ud(c,0,1);this.C.params.Hg=l;this.C.params.Xh=c;this.C.params.Ph=d;this.g.Hg=l;this.g.Xh=c;this.g.Ph=d;this.sj(this.B)};
g.h.XR=function(){g.Eq(this.element,"ytp-dragging")};
g.h.Ub=function(){return this.type};
g.h.sj=function(a){var b=Math.min(this.Qv(),this.N),c=this.Ov();g.fh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.ip(a);a={transform:"",top:"",left:""};b||(a.width="");c||(a.height="");var d=.96*this.g.Ph+2,e=this.g.Hg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.g.Xh+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.A.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.fh(this.element,a)};
g.h.ip=function(a){for(var b=0;b<a.length&&a[b]==this.B[b];b++);if(this.H||this.B.length>b)b=0,this.H=!1,this.B=[],this.F=[],this.G=[],this.D=null,g.xe(this.A);for(;b<a.length;b++)aua(this,a[b])};
g.h.Qv=function(){return 0};
g.h.Ov=function(){return 0};
g.h.toString=function(){return x8.O.toString.call(this)};
var eua=/^[^_-]+/;g.A(z8,w8);g.h=z8.prototype;g.h.Zq=function(a,b){var c=this.gk(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.ud();this.A=g.xF(c,{format:"RAW",Jb:d,withCredentials:!0});Pta(this.g,a)};
g.h.ar=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.Uw&&(b.asrs=1);d=g.uF(d,b);b=(0,g.z)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.g,e=b.getElementsByTagName("track"),l=e.length,m=0;m<l;m++){var n=e[m].getAttribute("formats"),q=c,r=e[m].getAttribute("lang_code"),v=e[m].getAttribute("lang_translated"),w=e[m].getAttribute("name"),B=e[m].getAttribute("kind"),G=e[m].getAttribute("id"),S="true"==e[m].getAttribute("lang_default"),
I="true"==e[m].getAttribute("cantran"),Oa=e[m].getAttribute("vss_id");l8(d,new g.eJ({formats:n,format:q,languageCode:r,languageName:v,name:w,kind:B,id:G,is_servable:!0,is_default:S,is_translateable:I,vss_id:Oa}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),m=b[e].getAttribute("lang_translated"),n=b[e].getAttribute("lang_original"),q=b[e].getAttribute("id"),r="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,
id:q,is_default:r},this.F[l.languageCode]=l.languageName,this.D.push(new g.dJ(l))}a()},this);
this.ud();this.A=g.xF(d,{format:"RAW",Jb:b,withCredentials:!0})};
g.h.gk=function(a){var b=this.B,c={v:this.C,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=L7(a));return b=g.uF(b,c)};
g.h.ud=function(){z8.O.ud.call(this);this.A&&this.A.abort()};
g.h.P=function(){this.ud();z8.O.P.call(this)};
g.A(A8,x8);A8.prototype.ra=function(){g.Eq(this.element,"ytp-rollup-mode");this.sj(this.ia,!0)};
A8.prototype.Qv=function(){var a=this.C.params.Yu;if(!this.S&&a){var b=g.te("SPAN");g.Je(b,"\u00a0"+(0,g.Na)("\u2014",a)+"\u00a0");g.fh(b,y8(this,this.g.gb));this.A.appendChild(b);this.S=b.offsetWidth;this.A.removeChild(b)}return this.S};
A8.prototype.Ov=function(){return this.C.params.Hn*B8(this)};
A8.prototype.sj=function(a,b){this.ia=a;if(B8(this)){for(var c=0,d=0;c<this.B.length&&d<a.length;c++)this.B[c]==a[d]&&d++;0<d&&d<a.length&&(a=this.B.concat(a.slice(d)));c=1;for(d=0;d<a.length;d++){var e=a[d];g.y(e.text)&&(c+=e.text.split("\n").length-1,e.C||0==d||c++)}c=this.C.params.Hn-c;c!=this.M&&(b||(0,window.isNaN)(this.M)||(g.R(this.element,"ytp-rollup-mode"),this.ea.Be()),d="",c&&(d="translateY("+Math.ceil(c*B8(this))+"px)"),g.fh(this.A,"transform",d),this.M=c);A8.O.sj.call(this,a)}else A8.O.sj.call(this,
a)};
g.A(C8,x8);C8.prototype.ip=function(a){var b=this.C.o;C8.O.ip.call(this,a);var c,d;for(a=a.length;a<b.length;a++){var e=b[a],f;d&&e.o==c?f=d:(f={},g.Aa(f,e.o),g.Aa(f,tua),c=e.o,d=f);aua(this,e,f)}};
g.A(D8,w8);g.h=D8.prototype;g.h.Zq=function(a,b){this.ud();var c=this.B.g[a.o];if(c){var d=1E3*c.index.Gm(c.index.Fi());this.A=new v8(0,this.W,c,function(c,f){b(c,a,f,d)},g.Y(this.W).Eg)}};
g.h.ar=function(a){g.Y(this.W).Eg?(l8(this.g,new g.eJ({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),l8(this.g,new g.eJ({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):l8(this.g,new g.eJ({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.ud=function(){D8.O.ud.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.gk=function(){return""};
g.h.P=function(){this.ud();D8.O.P.call(this)};
g.A(E8,w8);g.h=E8.prototype;g.h.Zq=function(a,b,c){var d=this.gk(a),e=(0,g.z)(function(c){this.B=null;b(c.responseText,a)},this);
this.ud();this.B=g.xF(d,{format:"RAW",Jb:e,withCredentials:!0});c&&this.A&&this.A.Zj!=a&&(this.A.xi=a)};
g.h.ar=function(a,b,c,d){this.C=c;if(this.A=d||null)for(b=0;b<this.A.captionTracks.length;b++)l8(this.g,this.A.captionTracks[b]);a()};
g.h.gk=function(a){var b=a.H,c={};if(this.C||a.A)c.fmt=this.C||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.uF(b,c)};
g.h.Pv=function(){return this.A?this.A.Zj:null};
g.h.Nv=function(){return this.A?this.A.xi:null};
g.h.ud=function(){E8.O.ud.call(this);this.B&&this.B.abort()};
g.h.P=function(){this.ud();E8.O.P.call(this)};
var L8={windowColor:"#080808",ci:0,textAlign:2,Hg:7,Ph:50,Xh:100,gb:{background:"#080808",Ke:.75,zh:0,color:"#fff",fontFamily:4,Bi:0,jh:1,offset:1}},kua=["none","raised","depressed","uniform","dropShadow"],mua="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" ");g.A(I8,g.XV);g.h=I8.prototype;g.h.P=function(){F8(this)||hua(this,!1);I8.O.P.call(this)};
g.h.load=function(a){I8.O.load.call(this);this.G=this.g.di();if(this.o||a)this.A?(a?this.mz(a,this.A):3!=this.g.Xa()&&this.o.Zq(this.A,(0,g.z)(this.mz,this),g.Y(this.g).experiments.g("legacy_default_captions")),this.g.xa("captionschanged",M7(this.A))):this.g.xa("onCaptionsTrackListChanged");else{var b;this.B.Ca?b=new D8(this.B.sa,this.g):this.B.captionTracks.length?b=new E8(this.B):b=new z8(this.B.Sl,this.B.videoId,this.B.ti||this.Y.ti||this.B.vf("yt:cc_default_lang")||this.Y.pa,this.B.Rl);this.o=
b;b.ar((0,g.z)(this.HN,this),!0,F8(this)?"vtt":void 0,this.g.di())}};
g.h.unload=function(){if(F8(this))for(var a=g.he("track",void 0,this.ea.g),b=0;b<a.length;b++)g.Ae(a[b]);else g.qu(this.ga),g.PV(this.g,"captions"),this.J=[],this.o&&this.o.ud(),this.F&&g.MV(this.g,this.F),this.us();I8.O.unload.call(this);(a=g.yV(this.g.app))&&a.C&&g.MK(a.C.A);this.g.xa("captionschanged",{})};
g.h.HN=function(){var a;if(this.M||dua(this))a=fua(this,this.M);if(F8(this))for(var b=k8(this.o.g,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.fJ(d),srclang:L7(d),src:this.o.gk(d)};d==a&&(e["default"]=1);this.W.app.F.Il([g.K("TRACK",e)])}else!this.A&&a&&K8(this,a),this.g.xa("onCaptionsTrackListChanged"),this.g.xa("onApiChange")};
g.h.BP=function(){this.loaded&&!F8(this)&&this.unload()};
g.h.mz=function(a,b,c,d){if(a){a=Xta(this.o,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:L7(b)};b.g&&(c.fromLangCode=b.o);g.GV(this.g,"cc",c);if(this.A!=J8(this)){if(this.M&&!g.MM(this.Y)&&!g.kP(this.Y)){g.qu(this.ga);b=c8({Hg:0,Ph:5,Xh:5,Hn:2,textAlign:0,yj:0,lang:"en"});this.L=[b];c=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.da||(d=new g.zR(g.XE()),g.M(this,d),this.da=d.element);d=b.end-b.start;var e=g.fJ(this.A);e&&this.L.push(new Z7(b.start,d,0,b.id,e));this.L.push(new Z7(b.start,
d,0,b.id,c[0]),new Z7(b.start,d,0,b.id,this.da,!0),new Z7(b.start,d,0,b.id,c[1],!0));g.MV(this.g,this.L);this.ga.Be()}if(this.M||g.MM(this.Y))M8(this,"module-enabled",!0),g.Y(this.g).experiments.g("legacy_default_captions")||(b=L7(this.A),c=H8(this,"recent-langs"),g.ra(c)||(c=[]),g.nb(c,b),c.unshift(b),3<c.length&&(c.length=3),this.G&&(this.G.xi=this.A));(b=g.yV(this.g.app))&&b.C&&g.MK(b.C.A)}g.MV(this.g,a);this.M=!1}};
g.h.HR=function(a){this.J.push(a);this.ba.Be()};
g.h.IR=function(a){g.nb(this.J,a);this.ba.Be()};
g.h.AO=function(a){if(a instanceof Y7){var b=this.H[a.id];b&&b.C!=a&&(b.dispose(),delete this.H[a.id],b=null);if(!b){var b=this.H,c=a.id;a:{var d=this.ea.Ua(),e=g.e_(this.ea,!0).height;switch(null!=a.params.gr?a.params.gr:a.params.rP?2:1<a.o.length?1:0){case 1:a=new C8(a,this.C,this.D,e,d.width,d.height);break a;case 2:a=new A8(a,this.C,this.D,e,d.width,d.height);break a;default:a=new x8(a,this.C,this.D,e,d.width,d.height)}}b[c]=a}}else b=a.windowId,this.N[b]||(this.N[b]=[]),this.N[b].push(a)};
g.h.OO=function(){gua(this,this.L);this.L=null};
g.h.AA=function(){this.ba.stop();bua(this.N);this.J.sort(g.nT);(0,g.F)(this.J,this.AO,this);g.Jb(this.H,function(a,b){!this.N[b]||this.F&&-1==this.F.indexOf(a.C)?(a.dispose(),delete this.H[b]):(a.element.parentNode||g.RV(this.g,a.element,5),a.sj(this.N[b]))},this)};
g.h.Nz=function(){G8(this,{},!0)};
g.h.Xp=function(){var a=L8.gb,a={background:a.background,backgroundOpacity:a.Ke,charEdgeStyle:a.zh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Bi,textOpacity:a.jh,windowColor:L8.windowColor,windowOpacity:L8.ci},b=H8(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.ys=function(a,b){var c={};g.Aa(c,H8(this,"display-settings"));g.Aa(c,a);G8(this,c,b);this.g.U("captionssettingschanged")};
g.h.us=function(){!F8(this)&&this.loaded&&(g.Jb(this.H,function(a,b){a.dispose();delete this.H[b]},this),this.AA())};
g.h.xB=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Ud(b,-2,4);this.ys({fontSizeIncrement:c});return c;case "reload":b&&!F8(this)&&K8(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.Y.Cb&&M8(this,"module-enabled",!!b);break;case "track":if(!this.o)return{};if(b){if(F8(this))break;if(!g.wa(b))break;if(g.Vb(b)){K8(this,null,!0);break}for(var d,e=k8(this.o.g,!0),c=0;c<e.length;c++){var f=e[c];f.o!=b.languageCode||d&&f.D!=b.languageName||(d=b.translationLanguage?
vta(f,b.translationLanguage):f)}!d||d==this.A&&this.loaded||K8(this,d,!0)}else return this.loaded&&this.A&&this.A!=J8(this)?M7(this.A):{};return"";case "tracklist":return this.o?(0,g.H)(k8(this.o.g,b&&b.includeAsr),function(a){return M7(a)}):[];
case "translationLanguages":return this.o?this.o.D:[];case "displaySettings":d=this.Xp();if(g.MM(this.Y)&&b&&g.wa(b))if(b.reset)this.Nz();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=iua(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=jua(b[c],d[c]);break;case "charEdgeStyle":f[c]=lua(b[c],d[c]);break;case "fontSizeIncrement":f[c]=oua(b[c],d[c]);break;case "fontFamilyOption":f.fontFamily=nua(b[c],d[c])}for(e in f)f[e+
"Override"]=!0;this.ys(f,!0);d=this.Xp()}d.fontFamilyOption=mua[d.fontFamily];d.charEdgeStyle=kua[d.charEdgeStyle];return d;case "sampleSubtitles":F8(this)||void 0==b||hua(this,!!b);break;case "xmlTrack":b&&this.Y.Cb&&!F8(this)&&K8(this,new g.eJ({languageName:b.name}),!1,b.xml)}};
g.h.FR=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.Y.Cb&&a.push("stickyLoading","xmlTrack");return a};
g.h.GR=function(){var a=this.A;return a?{cc:a.F}:{}};
g.h.yA=function(){this.loaded&&this.A?(M8(this,"module-enabled",!1),this.unload()):K8(this,this.A||fua(this,!0),!0)};
g.h.AK=function(){this.B.captionTracks.length&&(this.loaded&&this.unload(),cua(this)&&this.load())};
window._exportCheck==g.Ca&&g.oa("ytmod.player.captions",I8,void 0);})(_yt_player);
